spring:
  application:
    name: metastore #spring boot 快速启动
  datasource:
    url: jdbc:mysql:///metastore?useSSL=false     #数据库URL
    username: root                                #数据库登录名
    password: tiger                             #数据库登录密码
    driver-class-name: com.mysql.jdbc.Driver    #数据库驱动
  #  jpa.hibernate.ddl-auto: create-drop           #开启自动创建更新表
  jpa.properties.hibernate.hbm2ddl.auto: update   #开启自动创建更新表

server:
  session:
    timeout: 3600 #session 超时时间 (秒)
  port: 8080  #端口号